project_id = "mbvuwolsortpnnbwjene"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.referral]
verify_jwt = false
